./processor/ALU.v
./processor/Adder.v
./processor/Control_Unit.v
./processor/Main_Processor.v
./processor/adder_internal.v
./processor/black_box.v
./processor/comp.v
./processor/data_mem.v
./processor/full_adder.v
./processor/grey_box.v
./processor/halfadder.v
./processor/inst_mem.v
./processor/mux2_1_1bit.v
./processor/mux4_1_16bit.v
./processor/reg_file.v
./processor/stg_final.v
